name = "ReactionDiffusion"
uuid = "dcda7c7e-49c0-481c-982d-c35bedad83cd"
authors = ["Tom W. Hiscock", "Hugh Coleman"]
version = "0.1.10"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
DiffEqGPU = "071ae1c0-96b5-11e9-1965-c90190d839ea"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Groebner = "0b43b601-686d-58a3-8a1c-6623616c7cd4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqExponentialRK = "e0540318-69ee-4070-8777-9e2de6de23de"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
CUDA = "5.9.5"
Catalyst = "15.0.8"
DiffEqGPU = "3.9.0"
FFTW = "1.10.0"
FiniteDiff = "2.29.0"
ForwardDiff = "1.3.0"
Groebner = "0.9.5"
LinearAlgebra = "1.11.0"
Makie = "0.22.10"
ModelingToolkit = "9.83.0"
Observables = "0.5.5"
OrdinaryDiffEq = "6.102.0"
OrdinaryDiffEqExponentialRK = "1.8.0"
OrdinaryDiffEqRosenbrock = "1.18.1"
OrdinaryDiffEqTsit5 = "1.5.0"
Pipe = "1.3.0"
Printf = "1.11.0"
ProgressMeter = "1.11.0"
Random = "1.11.0"
Reexport = "1.2.2"
SciMLBase = "2.110.0"
StatsBase = "0.34.8"
SteadyStateDiffEq = "2.6.0"
SymbolicUtils = "3.31.0"
Symbolics = "6.55.0"
WGLMakie = "0.11.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
