name = "ReactionDiffusion"
uuid = "dcda7c7e-49c0-481c-982d-c35bedad83cd"
authors = ["Tom W. Hiscock"]
version = "0.1.10"

[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqExponentialRK = "e0540318-69ee-4070-8777-9e2de6de23de"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
Catalyst = "15.0.8"
Combinatorics = "1.0.3"
FFTW = "1.10.0"
LinearAlgebra = "1.11.0"
Makie = "0.22.10"
ModelingToolkit = "9.83.0"
OrdinaryDiffEq = "6.102.0"
OrdinaryDiffEqExponentialRK = "1.8.0"
OrdinaryDiffEqRosenbrock = "1.18.1"
Printf = "1.11.0"
ProgressLogging = "0.1.5"
ProgressMeter = "1.11.0"
Random = "1.11.0"
RecipesBase = "1.3.4"
SciMLBase = "2.110.0"
SteadyStateDiffEq = "2.6.0"
StructArrays = "0.7.1"
Symbolics = "6.55.0"
WGLMakie = "0.11.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
