[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ReactionDiffusion = "dcda7c7e-49c0-481c-982d-c35bedad83cd"

[compat]
Documenter = "1.8"
ReactionDiffusion = "0.2"
